language: python
python:
  - "2.6"
  - "2.7"
services:
  - postgresql
  # command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py check --settings=backlogr.settings.local
  - python manage.py migrate --noinput --settings=backlogr.settings.local
  - python manage.py test --noinput --settings=backlogr.settings.local
