# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_items', '0008_backlogitem_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='sequence_increment',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
