# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_items', '0009_backlogitem_sequence_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='item_short_id',
            field=models.CharField(default=0, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='backlogitem',
            name='sequence_increment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
