# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_items', '0010_auto_20160515_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogitem',
            name='item_short_id',
            field=models.CharField(default=0, editable=False, max_length=200, unique=True),
        ),
    ]
